### ISSUE TITLE
Create Genii Homeworld (Spawn Area)

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#117]
The Genii need a spawn area somewhere, so players who choose to join them can have a base of operations.

**Comment by DraksterAU** [comment]
Perhaps something like this ? 
http://www.planetminecraft.com/project/entire-aperture-laboratories-semi-accurate-ish-scale/

**Comment by mainesi** [comment]
world in progress. New world M1K-177

**Comment by mainesi** [comment]
Genni world complete

Since bot already added, follow these steps to add:

- /mw create M1K-177 normal 
- Do the usual load stuff
- Head east and gate is located near the village in the mountain
- Move the world spawn
- Protect the area that looks like it's been hand made (the mountain area also, about 150-200 blocks north of the gate area)

And then enjoy the world world

**Comment by Bysokar** [comment]
@mainesi Unbanned.
