### ISSUE TITLE
Residual reputation should be gained by a player depending on who the npc they killed is hostile with

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#92]
As written above

**Comment by DraksterAU** [comment]
Example:

Player kills wraith.

Faction 1 is: 
Atlantis Expedition (+5 rep for kill)
Faction 2 is:
Wraith (-5 rep for kill)

Because Wraith is losing reputation, by association players should GAIN reputation with all factions the Wraith are hostile with.
Because Atlantis Expedition is gaining reputation, by association players should LOSE reputation with all factions the Atlantis Expedition is hostile with.

**Comment by DraksterAU** [comment]
This has been implemented.
